---
title: "Analysis2"
author: "Aidan Mullan"
date: "2/26/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
PE <- read.csv("Data/Updates/PE_update_clean.csv")[,-1]
```


```{r}

## Looking at Contrast: Histogram and Boxplot
par(mfrow = c(1,2))
hist(PE$Contrast.Given, breaks = 20, main = "Figure 2a: Histogram of Contrast Given",
     xlab = "Contrast Given", ylab = "No. Patients", cex.main = 0.75)
boxplot(PE$Contrast.Given, main = "Figure 2b: Boxplot of Contrast Given", cex.main = 0.75, 
        ylab = "Contrast Given", yaxp = c(0,150,10))
par(mfrow = c(1,1))

## Looking at Effective Dose: Histogram and Boxplot
par(mfrow = c(1,2))
hist(PE$Eff.Dose, breaks = 20, main = "Figure 1a: Histogram of Effective Dose",
     xlab = "Effective Dose", ylab = "No. Patients", cex.main = 0.75)
axis(side = 1, at = seq(0,100,10))
boxplot(PE$Eff.Dose, main = "Figure 1b: Boxplot of Effective Dose", cex.main = 0.75, 
        ylab = "Effective Dose")
axis(side = 2, at = seq(0,100,10))
par(mfrow = c(1,1))
```

```{r}
## Creating Age and BMI groups
age_cuts <- c("<20", "20-30", "30-40", "40-50","50-60", "60-70",
              "70-80", "80-90", ">90")
PE$Age10 <- cut(PE$Age, breaks = c(-1,seq(20,90,10), 110), labels = age_cuts)

BMI_cuts <- c("10-15", "15-20", "20-25", "25-30","30-35", "35-40",
              "40-45", "45-50", "50-55", "55-60", ">60")
PE$BMI10 <- cut(PE$BMI, breaks = c(seq(10,60,5),92), labels = BMI_cuts)
summary(PE$Age10)
summary(PE$BMI10)

## Plotting Contrast by Age (10 Year Intervals)
contrast_by_age <- tapply(PE$Contrast.Given, PE$Age10, "mean")
plot(contrast_by_age, type = "l", ylab = "Contrast Given", xlab = "Age Group", xaxt = "n",
     main = "Avergae Contrast Administered by Age")
points(contrast_by_age)
axis(1, at = 1:9, labels = age_cuts, cex.axis = .75)

## Plotting Radiation by Age (10 Year Intervals)
rad_by_age <- tapply(PE$Eff.Dose, PE$Age10, "mean")
plot(rad_by_age, type = "l", ylab = "Effective Dose", xlab = "Age Group", xaxt = "n",
     main = "Mean Effective Dose by Age")
points(rad_by_age)
axis(1, at = 1:9, labels = age_cuts, cex.axis = .75)

## Plotting Contrast by BMI (5 Unit Intervals)

contrast_by_bmi <- tapply(PE$Contrast.Given, PE$BMI10, "mean")
plot(contrast_by_bmi, type = "l", ylab = "Contrast Given", xlab = "BMI Group", xaxt = "n",
     main = "Avergae Contrast Administered by BMI")
points(contrast_by_bmi)
axis(1, at = 1:11, labels = BMI_cuts, cex.axis = .75)

## Plotting Radiation by BMI (5 Unit Intervals)
rad_by_bmi <- tapply(PE$Eff.Dose, PE$BMI10, "mean")
plot(rad_by_bmi, type = "l", ylab = "Effective Dose", xlab = "BMI Group", xaxt = "n",
     main = "Mean Effective Dose by BMI")
points(rad_by_bmi)
axis(1, at = 1:11, labels = BMI_cuts, cex.axis = .75)
```

#####----------------------------------------------------

#####----------------------------------------------------

#####----------------------------------------------------


```{r}
## Effective Dosage Model

PE$Age_range <- cut(PE$Age, breaks = c(0,18,35,110), labels = c("<18", "18-35", ">35"))
PE$BMI_range <- cut(PE$BMI, breaks = c(0,25,40,100), labels = c("<25", "25-40", ">40"))

PE$Location2 <- as.factor(ifelse(PE$Location == "ICU", "ICU", "Other"))

effdose1 <- lm(log(Eff.Dose)~CT.Type+BMI_range+Age_range+Gender+Location, data = PE)
summary(effdose1)

effdose2 <- update(effdose1, .~.-Location)
anova(effdose1, effdose2)

effdose3 <- lm(log(Eff.Dose)~CT.Type+BMI_range+Age_range+Gender+Location2, data = PE)
anova(effdose1, effdose3)
summary(effdose3)

effdose3.aov <- aov(log(Eff.Dose)~CT.Type+BMI_range+Age_range+Gender+Location2, data = PE)
TukeyHSD(effdose3.aov, which = "CT.Type")
```

```{r}
## Contrast Model

contrast1 <- lm(Contrast.Given~CT.Type+BMI_range+Age_range+Gender+Location, data = PE)
summary(contrast1)

contrast2 <- update(contrast1, .~.-Age_range-BMI_range)
anova(contrast1, contrast2)
summary(contrast2)

contrast3 <- update(contrast2, .~.-Gender)
anova(contrast2, contrast3)
summary(contrast3)

contrast3.aov <- aov(Contrast.Given~CT.Type+Location, data = PE)
TukeyHSD(contrast3.aov)
```







