---
title: "PE_analysis"
author: "Aidan Mullan
date: "2/7/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Reading in data
PE_oldraw <- read.csv("Data/1st_Set/PE_clean.csv")
PE_old <- na.omit(subset(PE_oldraw[,c(3,4,5,7:13,16,17)], subset = Procedure == "Chest Only"))
```

```{r}
#####-----------------
## Summ Stats for Effective Dose and Contrast
#####-----------------

summary(PE_old$Eff.Dose)
summary(PE_old$Contrast.Given)

## Looking at Contrast alone: Histogram and Boxplot
par(mfrow = c(1,2))
hist(PE_old$Contrast.Given, breaks = 20, main = "Figure 2a: Histogram of Contrast Given",
     xlab = "Contrast Given", ylab = "No. Patients", cex.main = 0.75)
boxplot(PE_old$Contrast.Given, main = "Figure 2b: Boxplot of Contrast Given", cex.main = 0.75, 
        ylab = "Contrast Given")
axis(side = 2, at = seq(0,100,10))
par(mfrow = c(1,1))
summary(PE_old$Contrast.Given)

## Looking at Effective Dose Alone: Histogram and Boxplot
par(mfrow = c(1,2))
hist(PE_old$Eff.Dose, breaks = 20, main = "Figure 1a: Histogram of Effective Dose",
     xlab = "Effective Dose", ylab = "No. Patients", cex.main = 0.75)
axis(side = 1, at = seq(0,100,10))
boxplot(PE_old$Eff.Dose, main = "Figure 1b: Boxplot of Effective Dose", cex.main = 0.75, 
        ylab = "Effective Dose")
axis(side = 2, at = seq(0,100,10))
par(mfrow = c(1,1))



## Comparing Age and BMI groups for Eff Dose and Contrast
table(PE_old$Age_range, PE$BMI_range)

aggregate(Eff.Dose~Age_range+BMI_range, data = PE_old, FUN = "mean")
aggregate(Eff.Dose~Age_range, data = PE_old, FUN = "mean")
aggregate(Eff.Dose~BMI_range, data = PE_old, FUN = "mean")

## Contrast given by age group and BMI group
aggregate(Contrast.Given~Age_range+BMI_range, data = PE_old, FUN = "mean")
aggregate(Contrast.Given~Age_range, data = PE_old, FUN = "mean")
aggregate(Contrast.Given~BMI_range, data = PE_old, FUN = "mean")

## Comparing Scanner Type for Eff Dose and Contrast
aggregate(Eff.Dose~CT.Type, data = PE_old, FUN = "mean")
aggregate(Contrast.Given~CT.Type, data = PE_old, FUN = "mean")
aggregate(Eff.Dose~CT.Type, data = PE_old, FUN = "sd")
aggregate(Contrast.Given~CT.Type, data = PE_old, FUN = "sd")
```



```{r}
#####-------------------
## Summ Stats for Rate of PE
#####-------------------

PE$PE.Num <- ifelse(PE$Pulmonary.Embolism == "NO", 0, 1)
mean(PE$PE.Num)

## Positivity by Procedure Type
aggregate(PE.Num~Procedure, data = PE_old, FUN = "mean")

## Two-proportion Z test
p1 <- 0.1093; p2 <- 0.1229; n1 <- 2369; n2 <- 301
pp <- (p1*n1 + p2*n2) / (n1 + n2)
z <- (p1-p2)/(sqrt(pp*(1-pp)*(1/n1 + 1/n2)))
pnorm(z)

## Positivity by Age/BMI
mean(PE$PE.Num)
aggregate(PE.Num~Age_range, data = PE_old, FUN = "mean")
aggregate(PE.Num~BMI_range, data = PE_old, FUN = "mean")
aggregate(PE.Num~Age_range+BMI_range, data = PE_old, FUN = "mean")

## Positivity by Location
aggregate(PE.Num~Location, data = PE_old, FUN = "mean")
table(PE$Location)
```

```{r}
#####-----------------
## Summ Stats for Patients Testing Positive
####------------------

PE_Pos <- subset(PE_old, subset = PE.Num == 1)

## Type by Location
table(PE_Pos$Type, PE_Pos$Location)
table(PE_Pos$Type)
table(PE_Pos$Location)

## Type by Age
table(PE_Pos$Type, PE_Pos$Age_range)
table(PE_Pos$Age_range)

## Strain by Location
table(PE_Pos$Strain, PE_Pos$Location)
table(PE_Pos$Strain)

## Strain by Age
table(PE_Pos$Strain, PE_Pos$Age_range)
```

```{r}
#####------------------
## Positivity Model
#####------------------

positivity1 <- glm(PE.Num~Gender+Age_range+Eff.Dose+BMI_range+Procedure+CT.Type+Location,
               family = "binomial", data = PE_old)
summary(positivity1)

positivity2 <- update(positivity1, .~.-CT.Type)
summary(positivity2)
anova(positivity1, positivity2, test = "Chisq")

positivity3 <- update(positivity2, .~.-Age_range)
anova(positivity2, positivity3, test = "Chisq")
summary(positivity3)

positivity4 <- update(positivity3, .~.-Procedure)
anova(positivity3, positivity4, test = "Chisq") 
summary(positivity4)

positivity5 <- update(positivity4, .~.-Eff.Dose)
summary(positivity5)
anova(positivity4, positivity5, test = "Chisq")

positivity6 <- update(positivity5, .~.-Gender)
anova(positivity5, positivity6, test = "Chisq")
summary(positivity6)

positivity7 <- update(positivity6, .~.-BMI_range)
anova(positivity7, positivity6, test = "Chisq")
summary(positivity7)
## Final model has only Location
## Decided to re-model due to "double rule out" not having any positive test results
```

```{r}
## Removing double rule out procedure from analysis due to no positive test results
PE_nodub <- subset(PE_old, subset = Procedure != "Double rule out")
pos_nodub1 <- glm(PE.Num~Gender+Age_range+Eff.Dose+BMI_range+Procedure+CT.Type+Location,
               family = "binomial", data = PE_nodub)
summary(pos_nodub1)

pos_nodub2 <- update(pos_nodub1, .~.-Procedure-Age_range-Eff.Dose-CT.Type-Gender)
anova(pos_nodub1, pos_nodub2, test = "Chisq") 
summary(pos_nodub2)
## Final model has BMI and Location

```

```{r}
#####----------------
## Effective Dose Model
#####----------------

effdose1 <- lm(log(Eff.Dose)~CT.Type+BMI_range+Age_range+Gender+Location, data = PE_old)
summary(effdose1)

effdose2 <- update(effdose1, .~.-Location)
anova(effdose1, effdose2)
## Full model is final model
```

```{r}
#####----------------
## Contrast Model
#####----------------

contrast1 <- lm(Contrast.Given~CT.Type+BMI_range+Age_range+Gender+Location, data = PE_old)
summary(contrast1)
```

```{r}
#####---------------
## Plotting Contrast by Age and BMI
#####---------------

age_cuts <- c("<20", "20-30", "30-40", "40-50","50-60", "60-70",
              "70-80", "80-90", ">90")
PE_old$Age10 <- cut(PE_old$Age, breaks = c(-1,seq(20,90,10), 110), labels = age_cuts)

BMI_cuts <- c("10-15", "15-20", "20-25", "25-30","30-35", "35-40",
              "40-45", "45-50", "50-55", "55-60", ">60")
PE_old$BMI10 <- cut(PE_old$BMI, breaks = c(seq(10,60,5),92), labels = BMI_cuts)
summary(PE_old$Age10)
summary(PE_old$BMI10)

contrast_by_age <- tapply(PE_old$Contrast.Given, PE_old$Age10, "mean")
plot(contrast_by_age, type = "l", ylab = "Contrast Given", xlab = "Age Group", xaxt = "n",
     main = "Avergae Contrast Administered by Age")
points(contrast_by_age)
axis(1, at = 1:9, labels = age_cuts, cex.axis = .75)

contrast_by_bmi <- tapply(PE_old$Contrast.Given, PE_old$BMI10, "mean")
plot(contrast_by_bmi, type = "l", ylab = "Contrast Given", xlab = "BMI Group", xaxt = "n",
     main = "Avergae Contrast Administered by BMI")
points(contrast_by_bmi)
axis(1, at = 1:11, labels = BMI_cuts, cex.axis = .75)

rad_by_age <- tapply(PE_old$Eff.Dose, PE_old$Age10, "mean")
plot(rad_by_age, type = "l", ylab = "Effective Dose", xlab = "Age Group", xaxt = "n",
     main = "Mean Effective Dose by Age")
points(rad_by_age)
axis(1, at = 1:9, labels = age_cuts, cex.axis = .75)

rad_by_bmi <- tapply(PE_old$Eff.Dose, PE_old$BMI10, "mean")
plot(rad_by_bmi, type = "l", ylab = "Effective Dose", xlab = "BMI Group", xaxt = "n",
     main = "Mean Effective Dose by BMI")
points(rad_by_bmi)
axis(1, at = 1:11, labels = BMI_cuts, cex.axis = .75)
```









